// ChatModels.swift
// AmachHealth
//
// Data models for the Luma AI chat feature

import Foundation

// MARK: - Chat Messages

enum MessageRole: String, Codable {
    case user
    case assistant
    case system
}

struct ChatMessage: Identifiable, Codable {
    var id: UUID
    let role: MessageRole
    var content: String
    let timestamp: Date
    var metadata: ChatMessageMetadata?  // non-nil for Luma-initiated proactive messages

    init(id: UUID = UUID(), role: MessageRole, content: String, timestamp: Date = .now, metadata: ChatMessageMetadata? = nil) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.metadata = metadata
    }
}

// MARK: - Chat Session

struct ChatSession: Identifiable, Codable {
    var id: UUID
    var createdAt: Date
    var updatedAt: Date
    var messages: [ChatMessage]
    var storjUri: String?

    /// Distilled health narrative generated by Venice when this session is archived.
    /// Injected into future proactive Venice contexts for longitudinal memory.
    var healthSummary: String?

    var displayTitle: String {
        // Proactive sessions get a descriptive title based on the triggering metric
        if let first = messages.first(where: { $0.metadata?.isLumaInitiated == true }) {
            let label = first.content.prefix(60).description
            return "Luma: \(label)"
        }
        return messages.first(where: { $0.role == .user })?
            .content
            .prefix(50)
            .description
            .trimmingCharacters(in: .whitespacesAndNewlines)
            ?? "New Chat"
    }

    /// True if this session was initiated by a Luma proactive insight
    var isProactiveSession: Bool {
        messages.first?.metadata?.isLumaInitiated == true
    }

    init(id: UUID = UUID(), createdAt: Date = .now) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = createdAt
        self.messages = []
    }
}

// MARK: - API Request: POST /api/ai/chat

struct AIChatRequest: Encodable {
    let message: String
    let context: AIChatContext?
    let history: [AIChatHistoryMessage]
    let options: AIChatOptions?
}

struct AIChatContext: Encodable {
    let metrics: AIChatMetrics?
    let dateRange: AIChatDateRange?
    // Populated only for Luma-initiated proactive conversations
    let proactive: ProactiveInsightContext?
    let memory: AIChatMemoryCapsule?
    let userAddress: String?
    let encryptionKey: WalletEncryptionKey?
    /// Lab results (bloodwork, DEXA) and recent timeline events for Luma visibility
    let labData: LabDataContext?

    init(
        metrics: AIChatMetrics? = nil,
        dateRange: AIChatDateRange? = nil,
        proactive: ProactiveInsightContext? = nil,
        memory: AIChatMemoryCapsule? = nil,
        userAddress: String? = nil,
        encryptionKey: WalletEncryptionKey? = nil,
        labData: LabDataContext? = nil
    ) {
        self.metrics = metrics
        self.dateRange = dateRange
        self.proactive = proactive
        self.memory = memory
        self.userAddress = userAddress
        self.encryptionKey = encryptionKey
        self.labData = labData
    }
}

struct AIChatMetrics: Encodable {
    let steps: MetricContext?
    let heartRate: MetricContext?
    let hrv: MetricContext?
    let sleep: MetricContext?
    let exercise: MetricContext?
    let restingHeartRate: MetricContext?
    let vo2Max: MetricContext?
    let respiratoryRate: MetricContext?
    let recoveryScore: Int?
    let sleepDeepHours: MetricContext?
    let sleepRemHours: MetricContext?
}

struct MetricContext: Encodable {
    let average: Double?
    let min: Double?
    let max: Double?
    let latest: Double?
    let trend: String? // "improving" | "stable" | "declining"
}

struct AIChatDateRange: Encodable {
    let start: String
    let end: String
}

struct AIChatMemoryCapsule: Encodable {
    let activeGoals: [String]
    let activeConcerns: [String]
    let medications: [String]
    let conditions: [String]
    let recentSessionNotes: [String]
}

// MARK: - Conversation Memory Types (iOS)
//
// Lightweight mirror of the web ConversationMemory structures, used to build
// the memory capsule that gets injected into AIChatContext on-device.

enum FactCategory: String, Codable {
    case medication
    case condition
    case goal
    case concern
    case preference
}

enum MemoryImportance: String, Codable {
    case critical
    case high
    case medium
    case low
}

struct CriticalFact: Codable, Identifiable {
    let id: UUID
    let category: FactCategory
    let value: String
    let context: String?
    let dateIdentified: Date
    var isActive: Bool
}

struct SessionSummary: Codable, Identifiable {
    let id: UUID
    let date: Date
    let summary: String
    let topics: [String]
    let importance: MemoryImportance
    let messageCount: Int
}

@MainActor
final class ConversationMemoryStore: ObservableObject {
    static let shared = ConversationMemoryStore()

    @Published private(set) var facts: [CriticalFact] = []
    @Published private(set) var summaries: [SessionSummary] = []

    private let storageURL: URL = {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory())
        return docs.appendingPathComponent("amach_conversation_memory.json")
    }()

    private struct PersistedPayload: Codable {
        var facts: [CriticalFact]
        var summaries: [SessionSummary]
    }

    private init() {
        loadFromDisk()
    }

    func upsert(facts newFacts: [CriticalFact], summary: SessionSummary) {
        var mergedFacts = Dictionary(uniqueKeysWithValues: facts.map { ($0.id, $0) })
        for fact in newFacts {
            mergedFacts[fact.id] = fact
        }
        facts = Array(mergedFacts.values)

        if let idx = summaries.firstIndex(where: { $0.id == summary.id }) {
            summaries[idx] = summary
        } else {
            summaries.append(summary)
        }

        facts.sort { $0.dateIdentified < $1.dateIdentified }
        if facts.count > 200 {
            facts = Array(facts.suffix(200))
        }

        summaries.sort { $0.date < $1.date }
        if summaries.count > 40 {
            summaries = Array(summaries.suffix(40))
        }

        saveToDisk()
    }

    func buildMemoryCapsule() -> AIChatMemoryCapsule? {
        let activeFacts = facts.filter { $0.isActive }
        guard !activeFacts.isEmpty || !summaries.isEmpty else { return nil }

        func normalized(_ text: String, maxLen: Int) -> String {
            let collapsed = text.replacingOccurrences(
                of: "\\s+",
                with: " ",
                options: .regularExpression
            ).trimmingCharacters(in: .whitespacesAndNewlines)
            if collapsed.count <= maxLen { return collapsed }
            let idx = collapsed.index(collapsed.startIndex, offsetBy: maxLen)
            return String(collapsed[..<idx]).trimmingCharacters(in: .whitespacesAndNewlines) + "…"
        }

        func latestValues(for category: FactCategory, limit: Int?) -> [String] {
            let filtered = activeFacts.filter { $0.category == category }
                .sorted { $0.dateIdentified < $1.dateIdentified }
            let sliced = limit != nil ? Array(filtered.suffix(limit!)) : filtered
            return sliced.map { normalized($0.value, maxLen: 120) }
        }

        let activeGoals = latestValues(for: .goal, limit: 6)
        let activeConcerns = latestValues(for: .concern, limit: 6)
        // Bound medications/conditions for payload size: keep latest 20 each
        let medications = latestValues(for: .medication, limit: 20)
        let conditions = latestValues(for: .condition, limit: 20)

        let recentSummaries = summaries
            .sorted { $0.date < $1.date }
            .suffix(3)
            .map { summary in
                normalized(summary.summary, maxLen: 150)
            }

        if activeGoals.isEmpty,
           activeConcerns.isEmpty,
           medications.isEmpty,
           conditions.isEmpty,
           recentSummaries.isEmpty {
            return nil
        }

        return AIChatMemoryCapsule(
            activeGoals: activeGoals,
            activeConcerns: activeConcerns,
            medications: medications,
            conditions: conditions,
            recentSessionNotes: recentSummaries
        )
    }

    private func saveToDisk() {
        let payload = PersistedPayload(facts: facts, summaries: summaries)
        guard let data = try? JSONEncoder().encode(payload) else { return }
        try? data.write(to: storageURL, options: .atomic)
    }

    private func loadFromDisk() {
        guard
            let data = try? Data(contentsOf: storageURL),
            let payload = try? JSONDecoder().decode(PersistedPayload.self, from: data)
        else { return }

        facts = payload.facts
        summaries = payload.summaries
    }
}

// MARK: - Lab Data Context (bloodwork, DEXA, timeline events sent to Luma)

struct LabDataContext: Encodable {
    let bloodwork: [LabResultSummary]?
    let dexa: [DexaResultSummary]?
    let recentEvents: [TimelineEventSummary]?
}

struct LabResultSummary: Encodable {
    let date: String
    let glucose: Double?
    let hba1c: Double?
    let totalCholesterol: Double?
    let ldl: Double?
    let hdl: Double?
    let triglycerides: Double?
    let tsh: Double?
    let vitaminD: Double?
    let ferritin: Double?
    let notes: String?
}

struct DexaResultSummary: Encodable {
    let date: String
    let bodyFatPercent: Double?
    let leanMassKg: Double?
    let boneDensityTScore: Double?
    let visceralFat: Double?
    let androidGynoidRatio: Double?
    let notes: String?
}

struct TimelineEventSummary: Encodable {
    let date: String
    let type: String
    let summary: String
}

struct AIChatHistoryMessage: Codable {
    let role: String
    let content: String
}

struct AIChatOptions: Encodable {
    let mode: String // "quick" | "deep"
}

// MARK: - API Response

struct AIChatResponse: Decodable {
    let content: String
    let usage: AIChatUsage?
    let model: String?
}

struct AIChatUsage: Decodable {
    let promptTokens: Int?
    let completionTokens: Int?
    let totalTokens: Int?
}
